Reorganized plotting and pipeline
angelolab/TNBC_python_scripts pull request #16
Opened 2023-12-09 02:20 UTC by ngreenwald

Reorganized the figures, updating plotting, and tweaked some of the file names from the pipeline to be more informative.

2023-12-09 02:24 UTC, ngreenwald reviewed
@camisowers see below for highlights of the key points

2023-12-09 02:24 UTC, ngreenwald commented on python_files/nivo_outcomes.py
> +combined_df = pd.read_csv(os.path.join(base_dir, 'analysis_files/timepoint_combined_features.csv'))
I renamed `combined_df.csv` to `timepoint_combined_features.csv` so the filename is more informative. I think I made all the substitutions, but not sure.

2023-12-09 02:24 UTC, ngreenwald commented on python_files/nivo_outcomes.py
> +ranked_features_df = pd.concat(total_dfs)
I kept `total_dfs` as the list accumulator, but once they're combined together I switched the name to ranked_features_df to be more informative. Same with the output file name.

2023-12-09 02:24 UTC, ngreenwald commented on python_files/postprocessing/7_create_evolution_df.py
> +evolution_df.to_csv(os.path.join(output_dir, 'timepoint_evolution_features.csv'), index=False)
Renamed this to be more clear as well

2023-12-09 02:24 UTC, ngreenwald commented on python_files/postprocessing/7_create_evolution_df.py
> +combined_df.to_csv(os.path.join(analysis_dir, 'timepoint_combined_features.csv'), index=False)
This is now the primary input file

2023-12-11 18:15 UTC, camisowers requested changes
Two small additions, but other than that it all looks good.

2023-12-11 18:15 UTC, camisowers commented on python_files/postprocessing/7_create_evolution_df.py
> +evolution_df.to_csv(os.path.join(output_dir, 'timepoint_evolution_features.csv'), index=False)
Need to also change the file name read in on line 62 below.

2023-12-11 18:15 UTC, camisowers commented on python_files/postprocessing/7_create_evolution_df.py
> +combined_df.to_csv(os.path.join(analysis_dir, 'timepoint_combined_features.csv'), index=False)
Need to change this file name in the readme.

2023-12-11 18:46 UTC, ngreenwald commented
Good catches, thanks

2023-12-11 18:46 UTC, merged